import { StyleSheet } from "react-native";

export const globalStyles = {
  colors: {
    primary: "#3040d0",
    secondary: "#6c7bff",
    background: "#f9f9f9",
    text: "#000000",
    secondaryText: "#7f7f7f",
    card: "#ffffff",
    line: "#d4d4d4",
  },
  fonts: {
    primary: "DGBold",
    primarySemiBold: "DGSemiBold",
    secondary: "DMSans",
  },
};

export const globalStyleSheet = StyleSheet.create({
  button: {
    backgroundColor: globalStyles.colors.primary,
    paddingHorizontal: 25,
    borderRadius: 100,
    width: "100%",
    height: 65,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
  },
  secondaryButton: {
    backgroundColor: globalStyles.colors.secondary,
    paddingHorizontal: 25,
    borderRadius: 100,
    width: "100%",
    height: 65,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
    marginTop: 8,
  },
  formButton: {
    backgroundColor: globalStyles.colors.primary,
    paddingHorizontal: 25,
    borderRadius: 100,
    width: "100%",
    height: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
  },
  buttonText: {
    color: globalStyles.colors.card,
    fontFamily: globalStyles.fonts.primary,
    fontSize: 24,
  },
  iconButton: {
    backgroundColor: globalStyles.colors.card,
    borderRadius: 100,
    width: 50,
    height: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    borderColor: globalStyles.colors.line,
    borderWidth: 1,
  },
  textInput: {
    backgroundColor: globalStyles.colors.card,
    borderRadius: 8,
    width: "100%",
    height: 50,
    paddingHorizontal: 15,
    borderColor: globalStyles.colors.line,
    borderWidth: 1,
    fontSize: 20,
    fontFamily: globalStyles.fonts.primarySemiBold,
  },
  textAreaInput: {
    backgroundColor: globalStyles.colors.card,
    borderRadius: 8,
    width: "100%",
    height: 125,
    paddingHorizontal: 15,
    borderColor: globalStyles.colors.line,
    borderWidth: 1,
    fontSize: 20,
    fontFamily: globalStyles.fonts.primarySemiBold,
  },
  textInputTitle: {
    fontSize: 12,
    fontFamily: globalStyles.fonts.secondary,
    marginBottom: 2,
  },
  textInputContainer: {
    width: "100%",
    display: "flex",
    justifyContent: "flex-start",
    alignItems: "flex-start",
    flexDirection: "column",
    marginBottom: 15,
  },
  title: {
    fontSize: 48,
    fontFamily: globalStyles.fonts.primary,
    color: globalStyles.colors.text,
    width: "100%",
  },
  pageTitle: {
    fontSize: 20,
    fontFamily: globalStyles.fonts.primary,
    color: globalStyles.colors.secondaryText,
  },
  linkText: {
    fontFamily: globalStyles.fonts.primarySemiBold,
    fontSize: 18,
    textDecorationLine: "underline",
    color: globalStyles.colors.primary,
  },
  divider: {
    width: "100%",
    height: 1,
    backgroundColor: globalStyles.colors.line,
    marginTop: 25,
  },
});
